export const STANDARD_QUESTION_BANK = [
  {
    category: "Music",
    prompt: "What music gets you instantly on the dance floor?",
    options: JSON.stringify([
      "House & EDM",
      "Hip-Hop & R&B",
      "Latin & Reggaeton",
      "Indie & Alt Rock",
      "2000s Pop Throwbacks",
      "Techno & Underground",
    ]),
    traitTemplate: "Loves {value}",
    conversationPrompt: "Ask them what DJ or artist they are currently obsessed with!",
    order: 1,
  },
  {
    category: "Travel",
    prompt: "What's your biggest travel brag or experience?",
    options: JSON.stringify([
      "Lived in another country",
      "Backpacked internationally",
      "Taken a cross-country road trip",
      "Island hopped in the tropics",
      "Prefers staying close to home",
    ]),
    traitTemplate: "{value}",
    conversationPrompt: "Ask them where they traveled and what the craziest story was!",
    order: 2,
  },
  {
    category: "Language",
    prompt: "How many languages can you speak or order a drink in?",
    options: JSON.stringify([
      "1 language (English)",
      "2 languages bilingual",
      "3+ languages polyglot",
    ]),
    traitTemplate: "Speaks {value}",
    conversationPrompt: "Ask them to teach you how to say 'Cheers!' in another language!",
    order: 3,
  },
  {
    category: "Drink",
    prompt: "What's your go-to beverage order at the bar?",
    options: JSON.stringify([
      "Tequila or Mezcal",
      "Espresso Martini or Vodka",
      "Craft Beer or Cider",
      "Wine or Champagne",
      "Mocktails or Red Bull",
    ]),
    traitTemplate: "Drinks {value}",
    conversationPrompt: "Ask them if they've found their favorite drink on the menu tonight!",
    order: 4,
  },
  {
    category: "Roots",
    prompt: "Are you a local or from somewhere far away?",
    options: JSON.stringify([
      "Born & raised in this city",
      "Moved here within 2 years",
      "Visiting for the weekend",
      "Moved from another country",
    ]),
    traitTemplate: "{value}",
    conversationPrompt: "Ask them what their favorite secret spot in the city is!",
    order: 5,
  },
  {
    category: "Quirks",
    prompt: "What is your unexpected hidden talent?",
    options: JSON.stringify([
      "Can DJ or make music",
      "Cooks gourmet meals",
      "Fitness & marathon runner",
      "Astrology & tarot reader",
      "Insane trivia master",
    ]),
    traitTemplate: "{value}",
    conversationPrompt: "Ask them to prove or explain their hidden talent!",
    order: 6,
  },
  {
    category: "Vibe",
    prompt: "What is your energy style at social events?",
    options: JSON.stringify([
      "Center of the dance floor",
      "Lounge corner & deep talks",
      "Floating between all groups",
      "Checking out the DJ gear",
    ]),
    traitTemplate: "Vibe: {value}",
    conversationPrompt: "Ask them how long they plan to stay out tonight!",
    order: 7,
  },
  {
    category: "Birthday",
    prompt: "What season was your birthday in?",
    options: JSON.stringify([
      "Winter (Dec-Feb)",
      "Spring (Mar-May)",
      "Summer (Jun-Aug)",
      "Fall (Sep-Nov)",
    ]),
    traitTemplate: "Born in {value}",
    conversationPrompt: "Ask them when their exact birthday is and guess their zodiac sign!",
    order: 8,
  },
];
