export interface ThemePackDefinition {
  slug: string;
  name: string;
  description: string;
  targetAudience: string;
  tone: "playful" | "professional" | "warm";
  accentColor: string;
  iconName: string;
  cardSizeDefault: "5x5" | "4x4";
  isDefault?: boolean;
  order: number;
  questions: {
    category: string;
    prompt: string;
    options: string[];
    traitTemplate: string;
    conversationPrompt: string;
    order: number;
  }[];
}

export const SYSTEM_THEME_PACKS: ThemePackDefinition[] = [
  // 1. Nightlife & Party (Default Pilot Pack)
  {
    slug: "nightlife",
    name: "Nightlife & Party",
    description: "High-energy icebreaker for bars, lounges, club nights, and music events.",
    targetAudience: "Nightlife attendees, bar guests, club crowds, concertgoers",
    tone: "playful",
    accentColor: "#06B6D4", // Cyan
    iconName: "Flame",
    cardSizeDefault: "5x5",
    isDefault: true,
    order: 1,
    questions: [
      {
        category: "Music",
        prompt: "What music gets you instantly on the dance floor?",
        options: [
          "House & EDM",
          "Hip-Hop & R&B",
          "Latin & Reggaeton",
          "Indie & Alt Rock",
          "2000s Pop Throwbacks",
          "Techno & Underground",
        ],
        traitTemplate: "Loves {value}",
        conversationPrompt: "Ask them what DJ or artist they are currently obsessed with!",
        order: 1,
      },
      {
        category: "Travel",
        prompt: "What's your biggest travel brag or experience?",
        options: [
          "Lived in another country",
          "Backpacked internationally",
          "Taken a cross-country road trip",
          "Island hopped in the tropics",
          "Prefers staying close to home",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them where they traveled and what the craziest story was!",
        order: 2,
      },
      {
        category: "Language",
        prompt: "How many languages can you speak or order a drink in?",
        options: [
          "1 language (English)",
          "2 languages bilingual",
          "3+ languages polyglot",
        ],
        traitTemplate: "Speaks {value}",
        conversationPrompt: "Ask them what country they'd move to tomorrow if they could instantly speak the language!",
        order: 3,
      },
      {
        category: "Drink",
        prompt: "What's your go-to beverage order at the bar?",
        options: [
          "Tequila or Mezcal",
          "Espresso Martini or Vodka",
          "Whiskey or Dark Liquor",
          "Craft Beer or Cider",
          "Wine or Champagne",
          "Mocktails or Red Bull",
        ],
        traitTemplate: "Drinks {value}",
        conversationPrompt: "Ask them if they've found their favorite drink on the menu tonight!",
        order: 4,
      },
      {
        category: "Roots",
        prompt: "Are you a local or from somewhere far away?",
        options: [
          "Born & raised in this city",
          "Recent Transplant",
          "Moved here years ago",
          "Visiting for the weekend",
          "Moved from another country",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what their favorite secret spot in the city is!",
        order: 5,
      },
      {
        category: "Quirks",
        prompt: "What is your unexpected hidden talent?",
        options: [
          "Can DJ or make music",
          "Cooks gourmet meals",
          "Fitness & marathon runner",
          "Astrology & tarot reader",
          "Insane trivia master",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them to prove or explain their hidden talent!",
        order: 6,
      },
      {
        category: "Vibe",
        prompt: "What is your energy style at social events?",
        options: [
          "Center of the dance floor",
          "Lounge corner & deep talks",
          "Floating between all groups",
          "Checking out the DJ gear",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what song would get them sprinting to the dance floor!",
        order: 7,
      },
      {
        category: "Birthday",
        prompt: "What season was your birthday in?",
        options: [
          "Winter (Dec-Feb)",
          "Spring (Mar-May)",
          "Summer (Jun-Aug)",
          "Fall (Sep-Nov)",
        ],
        traitTemplate: "Born in {value}",
        conversationPrompt: "Ask them when their exact birthday is and guess their zodiac sign!",
        order: 8,
      },
    ],
  },

  // 2. Professional Networking & Tech
  {
    slug: "professional-networking",
    name: "Professional Networking",
    description: "Natural, high-value connection engine for business mixers, tech meetups, and founders.",
    targetAudience: "Tech professionals, founders, investors, consultants, corporate builders",
    tone: "professional",
    accentColor: "#3B82F6", // Blue
    iconName: "Briefcase",
    cardSizeDefault: "5x5",
    order: 2,
    questions: [
      {
        category: "Industry",
        prompt: "What industry or sector do you work in?",
        options: [
          "SaaS & AI Technology",
          "Finance & Venture Capital",
          "Healthcare & Biotech",
          "Creative, Media & Marketing",
          "Consulting & Professional Services",
          "Early-Stage Startup Founder",
        ],
        traitTemplate: "Works in {value}",
        conversationPrompt: "Ask them what the biggest trend or disruption in their sector is right now!",
        order: 1,
      },
      {
        category: "Function",
        prompt: "What best describes your primary role?",
        options: [
          "Engineering & Architecture",
          "Product Management & Strategy",
          "Sales, Growth & Partnerships",
          "Design, UX & Brand",
          "Operations, Legal & People",
        ],
        traitTemplate: "Specializes in {value}",
        conversationPrompt: "Ask them what problem they are currently trying to solve this quarter!",
        order: 2,
      },
      {
        category: "Career Stage",
        prompt: "What stage are you at in your career journey?",
        options: [
          "Early Career (First 3 Years)",
          "Mid-Career Specialist & Lead",
          "Director or Senior Executive",
          "Founder or Serial Entrepreneur",
          "Advisor or Angel Investor",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what the most pivotal career decision was that got them where they are!",
        order: 3,
      },
      {
        category: "Networking Goal",
        prompt: "What is your main goal for attending this event?",
        options: [
          "Hiring stellar talent",
          "Looking for my next career opportunity",
          "Fundraising or finding investors",
          "Meeting prospective enterprise clients",
          "Exchanging ideas with peers",
        ],
        traitTemplate: "Here for {value}",
        conversationPrompt: "Ask them what an ideal connection or introduction looks like for them tonight!",
        order: 4,
      },
      {
        category: "Workplace Style",
        prompt: "What does your everyday work setup look like?",
        options: [
          "100% Fully Remote Nomad",
          "In-Office 4-5 Days a Week",
          "Hybrid (2-3 days split)",
          "Coffee Shop & Co-working regular",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what their #1 productivity tip or home setup essential is!",
        order: 5,
      },
      {
        category: "Productivity",
        prompt: "What is your work superpower or obsession?",
        options: [
          "Inbox Zero fanatic",
          "Keyboard shortcuts & automation nerd",
          "Spreadsheets & modeling wizard",
          "Deep-work early morning riser",
          "Night owl late brainstormer",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them to reveal their favorite software tool or secret shortcut!",
        order: 6,
      },
      {
        category: "Media",
        prompt: "What do you listen to during your commute or focus time?",
        options: [
          "Tech & Business Podcasts",
          "Audiobooks on 1.5x speed",
          "Lo-Fi beats & synthwave",
          "High-energy EDM or Hip-Hop",
          "Pure silence or white noise",
        ],
        traitTemplate: "Focuses with {value}",
        conversationPrompt: "Ask them what book or podcast episode changed the way they think!",
        order: 7,
      },
      {
        category: "Dream Perk",
        prompt: "If you could add one dream perk to your work contract, what is it?",
        options: [
          "4-day work week permanently",
          "Unlimited international work stipend",
          "Personal in-office espresso barista",
          "Company-sponsored sabbatical year",
        ],
        traitTemplate: "Dreams of {value}",
        conversationPrompt: "Ask them how they would spend their ideal 3-day weekend!",
        order: 8,
      },
    ],
  },

  // 3. Conference & Trade Show
  {
    slug: "conference-tradeshow",
    name: "Conference & Expo",
    description: "Turn giant convention centers into approachable, engaging conversation circles.",
    targetAudience: "Conference delegates, trade show attendees, expo visitors, keynote crowds",
    tone: "professional",
    accentColor: "#8B5CF6", // Purple
    iconName: "Globe",
    cardSizeDefault: "5x5",
    order: 3,
    questions: [
      {
        category: "Attendance",
        prompt: "What role brings you to the conference this year?",
        options: [
          "First-time attendee",
          "Annual conference regular",
          "Featured speaker or panelist",
          "Exhibitor with a booth on expo floor",
          "Press, media or analyst",
        ],
        traitTemplate: "At the expo as a {value}",
        conversationPrompt: "Ask them what surprised them the most about this year's event!",
        order: 1,
      },
      {
        category: "Travel",
        prompt: "How far did you travel to get here?",
        options: [
          "Local in this metro area",
          "Drove in from a neighboring city",
          "Domestic flight across the country",
          "Flew in internationally",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them how their travel day went and what city they flew in from!",
        order: 2,
      },
      {
        category: "Agenda",
        prompt: "What session format do you get the most value from?",
        options: [
          "Main stage keynote announcements",
          "Hands-on technical workshops",
          "Interactive breakout roundtables",
          "Hallway track & spontaneous networking",
          "Evening parties & cocktail receptions",
        ],
        traitTemplate: "Values {value}",
        conversationPrompt: "Ask them what the best takeaway or quote they've heard so far was!",
        order: 3,
      },
      {
        category: "Energy",
        prompt: "What is your conference survival strategy?",
        options: [
          "Triple espresso before 9 AM",
          "Strategic afternoon power nap",
          "Powered by expo booth snacks & mints",
          "Running on pure caffeine & adrenaline",
        ],
        traitTemplate: "Survives with {value}",
        conversationPrompt: "Ask them how many miles their step tracker says they've walked today!",
        order: 4,
      },
      {
        category: "Swag",
        prompt: "What is your stance on the expo floor swag bag?",
        options: [
          "Gotta catch 'em all (takes every free tee)",
          "Only high-end tech gadgets & socks",
          "Minimalist (strictly zero-swag policy)",
          "Collecting gifts for the kids back home",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what the coolest or weirdest booth giveaway they've seen is!",
        order: 5,
      },
      {
        category: "Nightlife",
        prompt: "What is your plan when the expo floor closes tonight?",
        options: [
          "Hitting the sponsored afterparty",
          "Exploring local foodie restaurants",
          "Catching up on work emails in hotel room",
          "Late night drinks at the lobby bar",
        ],
        traitTemplate: "Evening plan: {value}",
        conversationPrompt: "Ask them if they've found any delicious food spots near the convention center!",
        order: 6,
      },
      {
        category: "Follow-Up",
        prompt: "How do you usually follow up with people you meet at conferences?",
        options: [
          "Immediate LinkedIn connect with a note",
          "Collect a stack of paper business cards",
          "Drop a calendar link right on the spot",
          "Take a selfie together to remember",
        ],
        traitTemplate: "Connects via {value}",
        conversationPrompt: "Ask them to exchange LinkedIn or contact info before you part ways!",
        order: 7,
      },
      {
        category: "Excitement",
        prompt: "What emerging tech or trend are you most excited to see demonstrated?",
        options: [
          "Autonomous AI agents & LLMs",
          "Clean energy & sustainability tech",
          "Robotics & hardware devices",
          "Fintech & digital payments infrastructure",
          "Enterprise cybersecurity & cloud",
        ],
        traitTemplate: "Most excited about {value}",
        conversationPrompt: "Ask them how they think that technology will impact their job in 3 years!",
        order: 8,
      },
    ],
  },

  // 4. Corporate Team Building
  {
    slug: "team-building",
    name: "Corporate Team Building",
    description: "Break cross-functional silos, foster genuine camaraderie, and celebrate teammates.",
    targetAudience: "Company all-hands, department retreats, offsites, cross-functional teams",
    tone: "warm",
    accentColor: "#10B981", // Emerald
    iconName: "Users",
    cardSizeDefault: "5x5",
    order: 4,
    questions: [
      {
        category: "Department",
        prompt: "Which department or team do you belong to?",
        options: [
          "Engineering, IT & Security",
          "Product & Design",
          "Sales, Marketing & Customer Success",
          "Operations, HR & People",
          "Finance, Legal & Executive",
        ],
        traitTemplate: "Teammate in {value}",
        conversationPrompt: "Ask them what project their team recently shipped that they are proud of!",
        order: 1,
      },
      {
        category: "Tenure",
        prompt: "How long have you been with the company?",
        options: [
          "New hire (under 6 months)",
          "1 to 2 years",
          "3 to 5 years",
          "Company veteran (5+ years)",
        ],
        traitTemplate: "Company tenure: {value}",
        conversationPrompt: "Ask them what surprised them the most during their first month on the job!",
        order: 2,
      },
      {
        category: "Collab Style",
        prompt: "What is your preferred collaboration style?",
        options: [
          "Async first with crisp Slack/docs",
          "Quick 5-minute huddle over video call",
          "Whiteboard brainstorm in the room",
          "Deep-focus solo then review",
        ],
        traitTemplate: "Prefers {value}",
        conversationPrompt: "Ask them what meeting on their calendar could have definitely been an email!",
        order: 3,
      },
      {
        category: "Office Fuel",
        prompt: "What beverage or snack keeps your day on track?",
        options: [
          "Iced cold brew or dark roast",
          "Flavored sparkling water / LaCroix",
          "Green tea, matcha, or herbal tea",
          "Electrolytes or energy drinks",
          "Office snack drawer grazer",
        ],
        traitTemplate: "Fueled by {value}",
        conversationPrompt: "Ask them what their favorite afternoon snack hack is!",
        order: 4,
      },
      {
        category: "WFH Reality",
        prompt: "What is your classic working-from-home signature?",
        options: [
          "Pet regularly makes guest cameos on camera",
          "Business shirt on top, sweatpants on bottom",
          "Walking pad treadmill during team all-hands",
          "Multiple monitors with 50 open browser tabs",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them if their pet has ever interrupted a high-stakes client call!",
        order: 5,
      },
      {
        category: "Hobbies",
        prompt: "What is your main hobby outside of work hours?",
        options: [
          "Cooking, baking or grilling",
          "Running, gym or outdoor sports",
          "Video games or board game nights",
          "Reading fiction or creative writing",
          "Playing music or seeing live concerts",
        ],
        traitTemplate: "Outside passion: {value}",
        conversationPrompt: "Ask them what they are currently reading, playing, or cooking this week!",
        order: 6,
      },
      {
        category: "Social Events",
        prompt: "What kind of team social do you enjoy most?",
        options: [
          "Trivia night or escape room challenge",
          "Relaxed happy hour drinks & tacos",
          "Catered team lunch with no agenda",
          "Outdoor park day or volunteer activity",
        ],
        traitTemplate: "Loves team {value}",
        conversationPrompt: "Ask them what their favorite team memory or laugh has been so far!",
        order: 7,
      },
      {
        category: "Superlative",
        prompt: "What award would your teammates most likely give you?",
        options: [
          "Fastest Slack emoji reactor",
          "Most organized calendar & notes",
          "Always has the best snack recommendations",
          "Calmest under tight deadlines",
        ],
        traitTemplate: "Known as {value}",
        conversationPrompt: "Ask them what emoji they use the most on Slack!",
        order: 8,
      },
    ],
  },

  // 5. Alumni & College Reunion
  {
    slug: "alumni-reunion",
    name: "Alumni & College Reunion",
    description: "Rekindle collegiate spirit, shared memories, and campus nostalgia across class years.",
    targetAudience: "University alumni, homecoming guests, greek reunions, class anniversaries",
    tone: "warm",
    accentColor: "#F59E0B", // Amber
    iconName: "GraduationCap",
    cardSizeDefault: "5x5",
    order: 5,
    questions: [
      {
        category: "Grad Era",
        prompt: "What graduation era do you represent?",
        options: [
          "Recent Graduate (Within 5 years)",
          "2010s Decade Alumni",
          "2000s Decade Alumni",
          "1990s Decade Alumni",
          "Golden Era (Before 1990)",
        ],
        traitTemplate: "Class of {value}",
        conversationPrompt: "Ask them what was the biggest campus tradition during their time as a student!",
        order: 1,
      },
      {
        category: "Major",
        prompt: "What was your broad academic discipline?",
        options: [
          "Engineering, Computer Science & STEM",
          "Business, Economics & Finance",
          "Humanities, Arts & Communication",
          "Biological Sciences & Pre-Med",
          "Social Sciences, Education & Law",
        ],
        traitTemplate: "Studied {value}",
        conversationPrompt: "Ask them what single course or professor had the greatest impact on them!",
        order: 2,
      },
      {
        category: "Residency",
        prompt: "Where do you call home today?",
        options: [
          "Still living in the college town area",
          "Moved to a major metropolitan city",
          "Settled in the quiet suburbs",
          "Living and working internationally",
        ],
        traitTemplate: "Currently {value}",
        conversationPrompt: "Ask them how often they get the chance to visit campus!",
        order: 3,
      },
      {
        category: "Memory",
        prompt: "What is your fondest recurring campus memory?",
        options: [
          "Football tailgates & game days",
          "Late-night diner runs after midnight",
          "All-nighters in the library with friends",
          "Dorm floor debates & late talks",
          "Spring music festivals on the quad",
        ],
        traitTemplate: "Fondest memory: {value}",
        conversationPrompt: "Ask them what their favorite late-night food order was after studying!",
        order: 4,
      },
      {
        category: "Involvement",
        prompt: "What was your main extracurricular activity on campus?",
        options: [
          "Greek Life (Fraternity / Sorority)",
          "Varsity or Club Sports athlete",
          "Student Government or Campus Paper",
          "Music, Theater or Performing Arts",
          "Volunteering & Community Service",
        ],
        traitTemplate: "Was involved in {value}",
        conversationPrompt: "Ask them if they still keep in touch with their old club or teammate crew!",
        order: 5,
      },
      {
        category: "College Habit",
        prompt: "What was your signature student habit?",
        options: [
          "Never missed an 8 AM lecture",
          "Master of hitting snooze 5 times",
          "Camped out in the same library cubicle",
          "Lived on instant noodles and iced coffee",
        ],
        traitTemplate: "{value} as a student",
        conversationPrompt: "Ask them if they could ever survive an 8 AM class today!",
        order: 6,
      },
      {
        category: "Reunion Bucket List",
        prompt: "What is the #1 thing on your reunion wishlist this weekend?",
        options: [
          "Visiting our favorite old college bar",
          "Reconnecting with freshman year roommates",
          "Touring all the new campus construction",
          "Catching the big game with old friends",
        ],
        traitTemplate: "Reunion goal: {value}",
        conversationPrompt: "Ask them which campus building or hangout spot they miss the most!",
        order: 7,
      },
      {
        category: "Journey",
        prompt: "How did you travel back for the reunion?",
        options: [
          "Flew in on a cross-country flight",
          "Took a nostalgic road trip",
          "Quick local drive across town",
          "Flew in from outside the country",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them who was the first classmate they bumped into when they arrived!",
        order: 8,
      },
    ],
  },

  // 6. Community & Faith Group
  {
    slug: "community-faith",
    name: "Community & Fellowship",
    description: "Warm, respectful, and family-friendly icebreakers for congregations, civic groups, and nonprofits.",
    targetAudience: "Faith communities, civic organizations, volunteer groups, neighborhood associations",
    tone: "warm",
    accentColor: "#EC4899", // Rose Pink
    iconName: "Heart",
    cardSizeDefault: "5x5",
    order: 6,
    questions: [
      {
        category: "Tenure",
        prompt: "How long have you been part of this community?",
        options: [
          "Visiting for the very first time today",
          "Joined within the last 6 months",
          "1 to 3 years regular",
          "Longtime pillar (5+ years)",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what first brought them to this community and what made them stay!",
        order: 1,
      },
      {
        category: "Outreach",
        prompt: "What type of service or outreach do you enjoy most?",
        options: [
          "Food pantry, meal prep & shelter drives",
          "Mentoring youth & student activities",
          "Music, choir & audiovisual production",
          "Greeting, hospitality & coffee team",
          "Community gardening & clean-ups",
        ],
        traitTemplate: "Serves through {value}",
        conversationPrompt: "Ask them about an impactful volunteer experience they've had recently!",
        order: 2,
      },
      {
        category: "Life Stage",
        prompt: "What life or family season describes you right now?",
        options: [
          "College student or young adult",
          "Newlywed or young couple",
          "Raising energetic kids at home",
          "Empty nester with grown kids",
          "Wise mentor / seasoned grandparent",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what piece of encouragement has meant the most to them lately!",
        order: 3,
      },
      {
        category: "Gathering",
        prompt: "What kind of community gathering is your favorite?",
        options: [
          "Casual potluck dinners & cookouts",
          "Small group weekly study circles",
          "Saturday charity workdays",
          "Annual retreats or summer picnics",
        ],
        traitTemplate: "Favorite event: {value}",
        conversationPrompt: "Ask them what signature dish they always bring to a potluck!",
        order: 4,
      },
      {
        category: "Free Time",
        prompt: "How do you recharge on a peaceful afternoon?",
        options: [
          "Working in the garden or nature walks",
          "Reading inspiring books or journaling",
          "Baking treats for family and neighbors",
          "Outdoor biking, hiking or sports",
        ],
        traitTemplate: "Recharges with {value}",
        conversationPrompt: "Ask them what book or activity brings them the most peace!",
        order: 5,
      },
      {
        category: "Morning",
        prompt: "What is your weekend morning routine?",
        options: [
          "Early sunrise walk with hot coffee",
          "Cooking a big breakfast feast with family",
          "Relaxing morning listening to acoustic music",
          "Busy morning heading out for sports and activities",
        ],
        traitTemplate: "Weekend style: {value}",
        conversationPrompt: "Ask them what their favorite breakfast comfort food is!",
        order: 6,
      },
      {
        category: "Roots",
        prompt: "Are you from this neighborhood or elsewhere?",
        options: [
          "Born and raised in this local area",
          "Moved here from another state",
          "International background",
          "Moved around frequently as a family",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what they appreciate most about living in this area!",
        order: 7,
      },
      {
        category: "Superpower",
        prompt: "What gift do friends always count on you for?",
        options: [
          "A compassionate listening ear",
          "Organizing events and getting people together",
          "Bringing over delicious homemade food",
          "Fixing practical things and lending tools",
        ],
        traitTemplate: "Always counted on for {value}",
        conversationPrompt: "Ask them who in their life taught them that skill or mindset!",
        order: 8,
      },
    ],
  },

  // 7. Wedding & Private Celebrations
  {
    slug: "wedding-celebration",
    name: "Wedding & Celebrations",
    description: "Melt table barriers and unite both sides of the guest list into one joyful celebration.",
    targetAudience: "Wedding receptions, rehearsal dinners, milestone anniversaries, birthday bashes",
    tone: "warm",
    accentColor: "#E11D48", // Rose Red
    iconName: "Wine",
    cardSizeDefault: "5x5",
    order: 7,
    questions: [
      {
        category: "Connection",
        prompt: "How do you know the honored couple or host?",
        options: [
          "Close friend of the couple",
          "Family member or relative",
          "College or school classmate",
          "Coworker or work colleague",
          "Plus-one discovering new friends tonight",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them to tell you a funny or heartwarming story about the couple!",
        order: 1,
      },
      {
        category: "Travel",
        prompt: "How far did you travel to celebrate tonight?",
        options: [
          "Local drive across town",
          "Drove a couple hours across state",
          "Took a flight across the country",
          "Traveled internationally to be here",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them where they flew in from and what their travel highlights were!",
        order: 2,
      },
      {
        category: "Party Role",
        prompt: "Where will everyone most likely find you tonight?",
        options: [
          "Front and center on the dance floor",
          "Catching up at the cocktail lounge bar",
          "Mingling with all the family tables",
          "Taking selfies in the photo booth",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what song will definitely get them on the dance floor tonight!",
        order: 3,
      },
      {
        category: "Dance Superpower",
        prompt: "What is your signature wedding dance move?",
        options: [
          "The synchronized line dance expert",
          "Singing every word to 90s/2000s classics",
          "Hype person cheering the dance circle",
          "Rhythmically nodding while holding a drink",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them what their all-time favorite wedding song is!",
        order: 4,
      },
      {
        category: "Drink",
        prompt: "What is your celebration drink of choice?",
        options: [
          "Champagne toast all evening",
          "The couple's signature cocktail",
          "Crisp craft beer or wine",
          "Refreshing zero-proof mocktail / sparkling water",
        ],
        traitTemplate: "Toasting with {value}",
        conversationPrompt: "Ask them what their favorite toast or speech so far tonight was!",
        order: 5,
      },
      {
        category: "Wedding Moment",
        prompt: "What wedding moment are you most looking forward to?",
        options: [
          "The heartfelt ceremony vows",
          "The romantic first dance",
          "Late-night sliders and dessert bar",
          "Tearful, hilarious speeches and toasts",
        ],
        traitTemplate: "Looking forward to {value}",
        conversationPrompt: "Ask them if they shed a tear during the ceremony!",
        order: 6,
      },
      {
        category: "History",
        prompt: "How long have you known the host or couple?",
        options: [
          "Known them since childhood or grade school",
          "Met during college or early twenties",
          "Bonded over the last 3-5 years",
          "Just met recently or tonight!",
        ],
        traitTemplate: "{value}",
        conversationPrompt: "Ask them when they first realized the couple was meant for each other!",
        order: 7,
      },
      {
        category: "Tomorrow",
        prompt: "What is your plan for tomorrow morning?",
        options: [
          "Sleeping in until afternoon",
          "Joining the post-wedding farewell brunch",
          "Catching an early morning flight back",
          "Exploring and sightseeing the host city",
        ],
        traitTemplate: "Tomorrow plan: {value}",
        conversationPrompt: "Ask them if they have any fun plans before heading home!",
        order: 8,
      },
    ],
  },

  // 8. General Social Mixer
  {
    slug: "general-mixer",
    name: "General Social Mixer",
    description: "The universal crowd-pleaser for community meetups, social clubs, and neighborhood gatherings.",
    targetAudience: "Social club members, casual meetups, singles mixers, community residents",
    tone: "playful",
    accentColor: "#14B8A6", // Teal
    iconName: "Sparkles",
    cardSizeDefault: "5x5",
    order: 8,
    questions: [
      {
        category: "Weekend Vibe",
        prompt: "How do you usually spend your ideal Saturday?",
        options: [
          "Out exploring new neighborhoods & coffee shops",
          "Cozy movie marathon & blanket burrito",
          "Outdoor hiking, cycling or farmers markets",
          "Social butterfly hitting multiple parties",
        ],
        traitTemplate: "Ideal weekend: {value}",
        conversationPrompt: "Ask them what their favorite weekend spot in the city is!",
        order: 1,
      },
      {
        category: "Food",
        prompt: "What food category could you eat every single week?",
        options: [
          "Tacos & authentic Mexican street food",
          "Handmade pasta & wood-fired pizza",
          "Sushi, ramen & Asian fusion",
          "Spicy curries & Mediterranean grills",
          "Burgers & craft brewery comfort food",
        ],
        traitTemplate: "Obsessed with {value}",
        conversationPrompt: "Ask them what local restaurant has the undisputed best food in town!",
        order: 2,
      },
      {
        category: "Pop Culture",
        prompt: "What is your current entertainment obsession?",
        options: [
          "Binge-watching prestige TV dramas",
          "Obsessed with true crime or comedy podcasts",
          "Cinema lover & independent films",
          "Gaming, esports or tabletop games",
          "Reading bestselling fiction",
        ],
        traitTemplate: "Entertainment fix: {value}",
        conversationPrompt: "Ask them what show or podcast they think everyone needs to experience!",
        order: 3,
      },
      {
        category: "Travel Dreams",
        prompt: "Where would you fly tomorrow if flights were free?",
        options: [
          "Street food tour in Tokyo or Bangkok",
          "Villa along the Amalfi coast in Italy",
          "Aurora camper van road trip in Iceland",
          "Tropical beach bungalow in the Caribbean",
          "Hiking the Swiss Alps or Patagonia",
        ],
        traitTemplate: "Dream destination: {value}",
        conversationPrompt: "Ask them what is at the absolute top of their bucket list!",
        order: 4,
      },
      {
        category: "Morning Fuel",
        prompt: "What gets you going in the morning?",
        options: [
          "Strong dark roast drip coffee",
          "Iced oat milk latte or cold brew",
          "Matcha latte or herbal tea",
          "Fresh fruit smoothie or green juice",
          "Sleep is my only fuel (slow riser)",
        ],
        traitTemplate: "Morning fuel: {value}",
        conversationPrompt: "Ask them if they are a genuine morning person or night owl!",
        order: 5,
      },
      {
        category: "Hidden Talent",
        prompt: "What is your low-key superpower?",
        options: [
          "Can remember quotes from almost any movie",
          "Can cook a delicious meal from random leftovers",
          "Never forgets a face or a name",
          "Master navigator with zero need for GPS",
        ],
        traitTemplate: "Superpower: {value}",
        conversationPrompt: "Ask them to demonstrate or explain how they developed that skill!",
        order: 6,
      },
      {
        category: "Conversation",
        prompt: "What kind of conversations do you enjoy the most?",
        options: [
          "Big philosophical ideas & future trends",
          "Hilarious storytelling & travel epics",
          "Deep, authentic talks about life goals",
          "Playful banter, pop culture debates & laughs",
        ],
        traitTemplate: "Enjoys {value}",
        conversationPrompt: "Ask them what the most interesting conversation they've had this week was!",
        order: 7,
      },
      {
        category: "Connection",
        prompt: "What inspired you to come out to this event tonight?",
        options: [
          "Wanted to expand my social circle & make friends",
          "A friend persuaded me to come along",
          "Love interactive games and icebreakers",
          "Live close by and wanted to check it out",
        ],
        traitTemplate: "Here because: {value}",
        conversationPrompt: "Ask them what other local events or groups they enjoy around town!",
        order: 8,
      },
    ],
  },
];
